sonar.projectKey=xvThomas_talk-backend
sonar.organization=xvthomas

sonar.sources=talk-libs,talk,mcp-owm,mcp-playground,mcp-ign-nav
sonar.exclusions=**/bin/**,**/vendor/**,**/tmp/**

sonar.tests=talk-libs,talk,mcp-owm,mcp-playground,mcp-ign-nav
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=\
  coverage-talk-libs/coverage.out,\
  coverage-talk/coverage.out,\
  coverage-mcp-owm/coverage.out,\
  coverage-mcp-playground/coverage.out,\
  coverage-mcp-ign-nav/coverage.out
